export {default as Header} from './Header'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as AboutUs } from './AboutUs'
export { default as Special } from './Special'
export { default as Menu } from './Menu'
export { default as BookTable} from './BookTable'
export { default as CookingIngredients } from './CookingIngredients'
export { default as Statics } from './Statics'
export { default as Reviews } from './Reviews'

